import random

STYLE_TAGS = [
    "[Calm]",
    "[Focus]",
    "[Rapid]",
    "[Detailed]",
    "[Brief]",
    "[Study]",
    "[Review]",
    "[Practice]",
    "[Check]",
    "[Note]",
    "[Explain]",
    "[Challenge]",
]

BASE_TRANSLATIONS = {
    "triangle": [
        "English: Compute the area and perimeter of the triangle defined by {points}.",
        "Francais: Calculez l'aire et le perimetre du triangle forme par {points}.",
        "Espanol: Calcula el area y el perimetro del triangulo con vertices {points}.",
        "Deutsch: Berechne Flaeche und Umfang des Dreiecks mit Punkten {points}.",
        "Italiano: Calcola area e perimetro del triangolo con vertici {points}.",
        "Portugues: Calcule a area e o perimetro do triangulo definido por {points}.",
        "Nederlands: Bepaal oppervlakte en omtrek van de driehoek met punten {points}.",
        "Svenska: Berakna arean och omkretsen for triangeln med {points}.",
        "Norsk: Finn areal og omkrets for trekanten med punktene {points}.",
        "Dansk: Udregn areal og omkreds for trekanten med punkterne {points}.",
        "Polski: Oblicz pole i obwod trojkata o wierzcholkach {points}.",
        "Turkce: {points} noktalarindan olusan ucgenin alanini ve cevresini hesapla.",
    ],
    "rectangle": [
        "English: Determine area and perimeter for the rectangle width {width} height {height}.",
        "Francais: Donnez l'aire et le perimetre du rectangle de largeur {width} et hauteur {height}.",
        "Espanol: Halla area y perimetro del rectangulo de ancho {width} y alto {height}.",
        "Deutsch: Bestimme Flaeche und Umfang des Rechtecks Breite {width} Hoehe {height}.",
        "Italiano: Trova area e perimetro del rettangolo di base {width} e altezza {height}.",
        "Portugues: Informe area e perimetro do retangulo de largura {width} e altura {height}.",
        "Nederlands: Bereken oppervlakte en omtrek van de rechthoek met breedte {width} en hoogte {height}.",
        "Svenska: Ange area och omkrets for rektangeln med bredd {width} och hojd {height}.",
        "Norsk: Finn areal og omkrets av rektangelet med bredde {width} og hoyde {height}.",
        "Dansk: Beregn areal og omkreds af rektanglet med bredde {width} og hojde {height}.",
        "Polski: Podaj pole i obwod prostokata o szerokosci {width} i wysokosci {height}.",
        "Turkce: Genisligi {width} yuksekligi {height} olan dortgenin alanini ve cevresini bul.",
    ],
    "circle": [
        "English: Provide area and circumference for the circle radius {radius}.",
        "Francais: Fournissez aire et circonference du cercle de rayon {radius}.",
        "Espanol: Indica area y circunferencia del circulo de radio {radius}.",
        "Deutsch: Bestimme Flaeche und Umfang des Kreises mit Radius {radius}.",
        "Italiano: Determina area e circonferenza del cerchio di raggio {radius}.",
        "Portugues: Diga area e circunferencia do circulo de raio {radius}.",
        "Nederlands: Geef oppervlakte en omtrek van de cirkel met straal {radius}.",
        "Svenska: Ange area och omkrets for cirkeln med radie {radius}.",
        "Norsk: Oppgi areal og omkrets for sirkelen med radius {radius}.",
        "Dansk: Angiv areal og omkreds for cirklen med radius {radius}.",
        "Polski: Podaj pole i obwod kola o promieniu {radius}.",
        "Turkce: Yaricapi {radius} olan cemberin alanini ve cevresini hesapla.",
    ],
    "segment": [
        "English: Measure the length of segment from {p1} to {p2}.",
        "Francais: Mesurez la longueur du segment allant de {p1} a {p2}.",
        "Espanol: Calcula la longitud del segmento entre {p1} y {p2}.",
        "Deutsch: Bestimme die Laenge der Strecke von {p1} nach {p2}.",
        "Italiano: Trova la lunghezza del segmento tra {p1} e {p2}.",
        "Portugues: Encontre o comprimento do segmento que liga {p1} a {p2}.",
        "Nederlands: Bepaal de lengte van het lijnstuk tussen {p1} en {p2}.",
        "Svenska: Rakna ut langden pa strackan mellan {p1} och {p2}.",
        "Norsk: Finn lengden pa linjestykket fra {p1} til {p2}.",
        "Dansk: Udregn laengden af linjestykket mellem {p1} og {p2}.",
        "Polski: Oblicz dlugosc odcinka laczacego {p1} i {p2}.",
        "Turkce: {p1} ile {p2} arasindaki dogru parcasinin uzunlugunu bul.",
    ],
    "polygon": [
        "English: Determine area and perimeter for the polygon passing through {points}.",
        "Francais: Calculez aire et perimetre du polygone passant par {points}.",
        "Espanol: Determina area y perimetro del poligono que pasa por {points}.",
        "Deutsch: Bestimme Flaeche und Umfang des Vielecks ueber {points}.",
        "Italiano: Trova area e perimetro del poligono con vertici {points}.",
        "Portugues: Calcule area e perimetro do poligono com vertices {points}.",
        "Nederlands: Bereken oppervlakte en omtrek van het veelhoek met punten {points}.",
        "Svenska: Ange area och omkrets for polygonen med punkterna {points}.",
        "Norsk: Finn areal og omkrets for polygonet med punktene {points}.",
        "Dansk: Udregn areal og omkreds af polygonen gennem punkterne {points}.",
        "Polski: Oblicz pole i obwod wielokata o wierzcholkach {points}.",
        "Turkce: {points} noktali cokgenin alanini ve cevresini belirt.",
    ],
    "point": [
        "English: Identify the coordinates of point P shown at {coordinate}.",
        "Francais: Indiquez les coordonnees du point P place en {coordinate}.",
        "Espanol: Menciona las coordenadas del punto P en {coordinate}.",
        "Deutsch: Gib die Koordinaten des Punktes P bei {coordinate} an.",
        "Italiano: Specifica le coordinate del punto P in {coordinate}.",
        "Portugues: Informe as coordenadas do ponto P situado em {coordinate}.",
        "Nederlands: Geef de coordinaten van punt P op {coordinate}.",
        "Svenska: Ange koordinaterna for punkt P vid {coordinate}.",
        "Norsk: Oppgi koordinatene til punkt P ved {coordinate}.",
        "Dansk: Angiv koordinaterne for punkt P ved {coordinate}.",
        "Polski: Podaj wspolrzedne punktu P w {coordinate}.",
        "Turkce: {coordinate} konumundaki P noktasinin koordinatlarini yaz.",
    ],
    "line": [
        "English: Report slope and intercept for the line {equation}.",
        "Francais: Donnez pente et ordonnee a l'origine pour la droite {equation}.",
        "Espanol: Indica pendiente e interseccion de la recta {equation}.",
        "Deutsch: Notiere Steigung und Achsenabschnitt der Geraden {equation}.",
        "Italiano: Indica coefficiente angolare e intercetta della retta {equation}.",
        "Portugues: Informe inclinacao e intercepto da reta {equation}.",
        "Nederlands: Geef helling en intercept van de lijn {equation}.",
        "Svenska: Ange lutning och intercept for linjen {equation}.",
        "Norsk: Oppgi helning og skjaring for linjen {equation}.",
        "Dansk: Angiv haeldning og skaering for linjen {equation}.",
        "Polski: Podaj nachylenie i wyraz wolny prostej {equation}.",
        "Turkce: {equation} dogrusunun egimini ve kesisimini belirt.",
    ],
    "scatter": [
        "English: Determine {detail} from the scatter plot.",
        "Francais: Determinez {detail} a partir du nuage de points.",
        "Espanol: Determina {detail} segun el diagrama de dispersion.",
        "Deutsch: Bestimme {detail} aus dem Streudiagramm.",
        "Italiano: Ricava {detail} dal grafico a dispersione.",
        "Portugues: Encontre {detail} no grafico de dispersao.",
        "Nederlands: Bepaal {detail} uit het spreidingsdiagram.",
        "Svenska: Ta reda pa {detail} fran spridningsdiagrammet.",
        "Norsk: Finn {detail} fra spredningsdiagrammet.",
        "Dansk: Fastlaeg {detail} ud fra spredningsplottet.",
        "Polski: Wyznacz {detail} z wykresu rozrzutu.",
        "Turkce: Sacilim grafiginden {detail} belirle.",
    ],
    "line_plot": [
        "English: Identify {detail} for the plotted line.",
        "Francais: Identifiez {detail} pour la droite tracee.",
        "Espanol: Identifica {detail} para la recta dibujada.",
        "Deutsch: Bestimme {detail} der dargestellten Gerade.",
        "Italiano: Individua {detail} della retta disegnata.",
        "Portugues: Indique {detail} da linha representada.",
        "Nederlands: Bepaal {detail} van de getekende lijn.",
        "Svenska: Ange {detail} for linjen i diagrammet.",
        "Norsk: Oppgi {detail} for linjen som vises.",
        "Dansk: Giv {detail} for den viste linje.",
        "Polski: Okresl {detail} dla narysowanej prostej.",
        "Turkce: Cizilen dogru icin {detail} belirt.",
    ],
    "histogram": [
        "English: State {detail} based on the histogram.",
        "Francais: Indiquez {detail} a partir de l'histogramme.",
        "Espanol: Di {detail} segun el histograma.",
        "Deutsch: Gib {detail} anhand des Histogramms an.",
        "Italiano: Riporta {detail} dal istogramma.",
        "Portugues: Informe {detail} com base no histograma.",
        "Nederlands: Meld {detail} vanuit het histogram.",
        "Svenska: Ange {detail} utifran histogrammet.",
        "Norsk: Oppgi {detail} basert pa histogrammet.",
        "Dansk: Angiv {detail} fra histogrammet.",
        "Polski: Podaj {detail} na podstawie histogramu.",
        "Turkce: Histograma gore {detail} belirt.",
    ],
    "bar_chart": [
        "English: Tell {detail} from the bar chart.",
        "Francais: Donnez {detail} depuis le diagramme en barres.",
        "Espanol: Indica {detail} del grafico de barras.",
        "Deutsch: Teile {detail} aus dem Balkendiagramm mit.",
        "Italiano: Comunica {detail} dal grafico a barre.",
        "Portugues: Apresente {detail} do grafico de barras.",
        "Nederlands: Geef {detail} vanuit het staafdiagram.",
        "Svenska: Redovisa {detail} fran stapeldiagrammet.",
        "Norsk: Oppgi {detail} fra stolpediagrammet.",
        "Dansk: Angiv {detail} fra sojlediagrammet.",
        "Polski: Podaj {detail} z wykresu slupkowego.",
        "Turkce: Sutun grafiginden {detail} bildir.",
    ],
    "stats": [
        "English: Using the list {numbers}, deliver mean median and variance.",
        "Francais: A partir de {numbers}, donnez moyenne mediane et variance.",
        "Espanol: Con {numbers}, proporciona media mediana y varianza.",
        "Deutsch: Berechne Mittelwert Median und Varianz fur {numbers}.",
        "Italiano: Calcola media mediana e varianza dei numeri {numbers}.",
        "Portugues: Informe media mediana e variancia para {numbers}.",
        "Nederlands: Geef gemiddelde mediaan en variantie voor {numbers}.",
        "Svenska: Berakna medel median och varians for {numbers}.",
        "Norsk: Finn gjennomsnitt median og variasjon for {numbers}.",
        "Dansk: Udregn gennemsnit median og varians for {numbers}.",
        "Polski: Podaj srednia mediane i wariancje liczb {numbers}.",
        "Turkce: {numbers} listesinin ortalamasini medianini ve varyansini hesapla.",
    ],
    "integral": [
        "English: Evaluate the integral of {expr} from 0 to 1.",
        "Francais: Evaluez l'integrale de {expr} entre 0 et 1.",
        "Espanol: Evalua la integral de {expr} entre 0 y 1.",
        "Deutsch: Bestimme das Integral von {expr} zwischen 0 und 1.",
        "Italiano: Calcola l'integrale di {expr} tra 0 e 1.",
        "Portugues: Resolva a integral de {expr} de 0 a 1.",
        "Nederlands: Bereken de integraal van {expr} van 0 tot 1.",
        "Svenska: Integrera {expr} fran 0 till 1.",
        "Norsk: Integrer {expr} fra 0 til 1.",
        "Dansk: Integrer {expr} fra 0 til 1.",
        "Polski: Oblicz calke z {expr} od 0 do 1.",
        "Turkce: {expr} fonksiyonunu 0 ile 1 araliginda integrallen.",
    ],
    "probability": [
        "English: What is the probability of rolling <= {favorable} on a {sides}-sided die?",
        "Francais: Quelle est la probabilite d'obtenir <= {favorable} avec un de a {sides} faces?",
        "Espanol: Cual es la probabilidad de sacar <= {favorable} en un dado de {sides} caras?",
        "Deutsch: Wie gross ist die Wahrscheinlichkeit fuer <= {favorable} bei einem {sides}-seitigen Wuerfel?",
        "Italiano: Qual e la probabilita di ottenere <= {favorable} con un dado da {sides} facce?",
        "Portugues: Qual a probabilidade de obter <= {favorable} em um dado de {sides} lados?",
        "Nederlands: Wat is de kans op <= {favorable} met een {sides}-zijdige dobbelsteen?",
        "Svenska: Vad ar sannolikheten for <= {favorable} pa en {sides}-sidig tarning?",
        "Norsk: Hva er sannsynligheten for <= {favorable} pa en {sides}-siders terning?",
        "Dansk: Hvad er sandsynligheden for <= {favorable} pa en {sides}-siders terning?",
        "Polski: Jakie jest prawdopodobienstwo wylosowania <= {favorable} kostka o {sides} scianach?",
        "Turkce: {sides} yuzlu zarla <= {favorable} gelme olasiligi nedir?",
    ],
}

_requirement_counts = {key: len(STYLE_TAGS) * len(value) for key, value in BASE_TRANSLATIONS.items()}
for key, count in _requirement_counts.items():
    if count < 100:
        raise ValueError(f"Template bank for {key} must have at least 100 variants, has {count}")


def multilingual_prompt(key: str, **kwargs) -> str:
    templates = BASE_TRANSLATIONS[key]
    style = random.choice(STYLE_TAGS)
    template = random.choice(templates)
    return f"{style} {template.format(**kwargs)}"
